# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/binh/BTL_HTN_GTN_final/la_bd_project/la_bd_project.srcs/sources_1/bd/la_system/ip/la_system_smartconnect_0_0/la_system_smartconnect_0_0.xci
# IP: The module: 'la_system_smartconnect_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/binh/BTL_HTN_GTN_final/la_bd_project/la_bd_project.gen/sources_1/bd/la_system/ip/la_system_smartconnect_0_0/bd_0/bd_94ec.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/binh/BTL_HTN_GTN_final/la_bd_project/la_bd_project.gen/sources_1/bd/la_system/ip/la_system_smartconnect_0_0/bd_0/ip/ip_0/bd_94ec_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/binh/BTL_HTN_GTN_final/la_bd_project/la_bd_project.gen/sources_1/bd/la_system/ip/la_system_smartconnect_0_0/bd_0/ip/ip_1/bd_94ec_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/binh/BTL_HTN_GTN_final/la_bd_project/la_bd_project.gen/sources_1/bd/la_system/ip/la_system_smartconnect_0_0/bd_0/ip/ip_2/bd_94ec_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/binh/BTL_HTN_GTN_final/la_bd_project/la_bd_project.gen/sources_1/bd/la_system/ip/la_system_smartconnect_0_0/bd_0/ip/ip_3/bd_94ec_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/binh/BTL_HTN_GTN_final/la_bd_project/la_bd_project.gen/sources_1/bd/la_system/ip/la_system_smartconnect_0_0/bd_0/ip/ip_4/bd_94ec_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/binh/BTL_HTN_GTN_final/la_bd_project/la_bd_project.gen/sources_1/bd/la_system/ip/la_system_smartconnect_0_0/bd_0/ip/ip_5/bd_94ec_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/binh/BTL_HTN_GTN_final/la_bd_project/la_bd_project.gen/sources_1/bd/la_system/ip/la_system_smartconnect_0_0/bd_0/ip/ip_6/bd_94ec_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/binh/BTL_HTN_GTN_final/la_bd_project/la_bd_project.gen/sources_1/bd/la_system/ip/la_system_smartconnect_0_0/bd_0/ip/ip_7/bd_94ec_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/binh/BTL_HTN_GTN_final/la_bd_project/la_bd_project.gen/sources_1/bd/la_system/ip/la_system_smartconnect_0_0/bd_0/ip/ip_8/bd_94ec_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/binh/BTL_HTN_GTN_final/la_bd_project/la_bd_project.gen/sources_1/bd/la_system/ip/la_system_smartconnect_0_0/bd_0/ip/ip_9/bd_94ec_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/binh/BTL_HTN_GTN_final/la_bd_project/la_bd_project.gen/sources_1/bd/la_system/ip/la_system_smartconnect_0_0/bd_0/ip/ip_10/bd_94ec_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/binh/BTL_HTN_GTN_final/la_bd_project/la_bd_project.gen/sources_1/bd/la_system/ip/la_system_smartconnect_0_0/bd_0/ip/ip_11/bd_94ec_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/binh/BTL_HTN_GTN_final/la_bd_project/la_bd_project.gen/sources_1/bd/la_system/ip/la_system_smartconnect_0_0/bd_0/ip/ip_12/bd_94ec_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/binh/BTL_HTN_GTN_final/la_bd_project/la_bd_project.gen/sources_1/bd/la_system/ip/la_system_smartconnect_0_0/bd_0/ip/ip_1/bd_94ec_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/binh/BTL_HTN_GTN_final/la_bd_project/la_bd_project.gen/sources_1/bd/la_system/ip/la_system_smartconnect_0_0/bd_0/ip/ip_1/bd_94ec_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/binh/BTL_HTN_GTN_final/la_bd_project/la_bd_project.gen/sources_1/bd/la_system/ip/la_system_smartconnect_0_0/bd_0/ip/ip_5/bd_94ec_s00a2s_0_ooc.xdc

# XDC: /home/binh/BTL_HTN_GTN_final/la_bd_project/la_bd_project.gen/sources_1/bd/la_system/ip/la_system_smartconnect_0_0/bd_0/ip/ip_6/bd_94ec_sarn_0_ooc.xdc

# XDC: /home/binh/BTL_HTN_GTN_final/la_bd_project/la_bd_project.gen/sources_1/bd/la_system/ip/la_system_smartconnect_0_0/bd_0/ip/ip_7/bd_94ec_srn_0_ooc.xdc

# XDC: /home/binh/BTL_HTN_GTN_final/la_bd_project/la_bd_project.gen/sources_1/bd/la_system/ip/la_system_smartconnect_0_0/bd_0/ip/ip_8/bd_94ec_sawn_0_ooc.xdc

# XDC: /home/binh/BTL_HTN_GTN_final/la_bd_project/la_bd_project.gen/sources_1/bd/la_system/ip/la_system_smartconnect_0_0/bd_0/ip/ip_9/bd_94ec_swn_0_ooc.xdc

# XDC: /home/binh/BTL_HTN_GTN_final/la_bd_project/la_bd_project.gen/sources_1/bd/la_system/ip/la_system_smartconnect_0_0/bd_0/ip/ip_10/bd_94ec_sbn_0_ooc.xdc

# XDC: /home/binh/BTL_HTN_GTN_final/la_bd_project/la_bd_project.gen/sources_1/bd/la_system/ip/la_system_smartconnect_0_0/bd_0/ip/ip_11/bd_94ec_m00s2a_0_ooc.xdc

# XDC: /home/binh/BTL_HTN_GTN_final/la_bd_project/la_bd_project.gen/sources_1/bd/la_system/ip/la_system_smartconnect_0_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'la_system_smartconnect_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/binh/BTL_HTN_GTN_final/la_bd_project/la_bd_project.gen/sources_1/bd/la_system/ip/la_system_smartconnect_0_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'la_system_smartconnect_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/binh/BTL_HTN_GTN_final/la_bd_project/la_bd_project.srcs/sources_1/bd/la_system/ip/la_system_smartconnect_0_0/la_system_smartconnect_0_0.xci
# IP: The module: 'la_system_smartconnect_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/binh/BTL_HTN_GTN_final/la_bd_project/la_bd_project.gen/sources_1/bd/la_system/ip/la_system_smartconnect_0_0/bd_0/bd_94ec.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/binh/BTL_HTN_GTN_final/la_bd_project/la_bd_project.gen/sources_1/bd/la_system/ip/la_system_smartconnect_0_0/bd_0/ip/ip_0/bd_94ec_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/binh/BTL_HTN_GTN_final/la_bd_project/la_bd_project.gen/sources_1/bd/la_system/ip/la_system_smartconnect_0_0/bd_0/ip/ip_1/bd_94ec_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/binh/BTL_HTN_GTN_final/la_bd_project/la_bd_project.gen/sources_1/bd/la_system/ip/la_system_smartconnect_0_0/bd_0/ip/ip_2/bd_94ec_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/binh/BTL_HTN_GTN_final/la_bd_project/la_bd_project.gen/sources_1/bd/la_system/ip/la_system_smartconnect_0_0/bd_0/ip/ip_3/bd_94ec_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/binh/BTL_HTN_GTN_final/la_bd_project/la_bd_project.gen/sources_1/bd/la_system/ip/la_system_smartconnect_0_0/bd_0/ip/ip_4/bd_94ec_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/binh/BTL_HTN_GTN_final/la_bd_project/la_bd_project.gen/sources_1/bd/la_system/ip/la_system_smartconnect_0_0/bd_0/ip/ip_5/bd_94ec_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/binh/BTL_HTN_GTN_final/la_bd_project/la_bd_project.gen/sources_1/bd/la_system/ip/la_system_smartconnect_0_0/bd_0/ip/ip_6/bd_94ec_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/binh/BTL_HTN_GTN_final/la_bd_project/la_bd_project.gen/sources_1/bd/la_system/ip/la_system_smartconnect_0_0/bd_0/ip/ip_7/bd_94ec_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/binh/BTL_HTN_GTN_final/la_bd_project/la_bd_project.gen/sources_1/bd/la_system/ip/la_system_smartconnect_0_0/bd_0/ip/ip_8/bd_94ec_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/binh/BTL_HTN_GTN_final/la_bd_project/la_bd_project.gen/sources_1/bd/la_system/ip/la_system_smartconnect_0_0/bd_0/ip/ip_9/bd_94ec_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/binh/BTL_HTN_GTN_final/la_bd_project/la_bd_project.gen/sources_1/bd/la_system/ip/la_system_smartconnect_0_0/bd_0/ip/ip_10/bd_94ec_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/binh/BTL_HTN_GTN_final/la_bd_project/la_bd_project.gen/sources_1/bd/la_system/ip/la_system_smartconnect_0_0/bd_0/ip/ip_11/bd_94ec_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/binh/BTL_HTN_GTN_final/la_bd_project/la_bd_project.gen/sources_1/bd/la_system/ip/la_system_smartconnect_0_0/bd_0/ip/ip_12/bd_94ec_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/binh/BTL_HTN_GTN_final/la_bd_project/la_bd_project.gen/sources_1/bd/la_system/ip/la_system_smartconnect_0_0/bd_0/ip/ip_1/bd_94ec_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/binh/BTL_HTN_GTN_final/la_bd_project/la_bd_project.gen/sources_1/bd/la_system/ip/la_system_smartconnect_0_0/bd_0/ip/ip_1/bd_94ec_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/binh/BTL_HTN_GTN_final/la_bd_project/la_bd_project.gen/sources_1/bd/la_system/ip/la_system_smartconnect_0_0/bd_0/ip/ip_5/bd_94ec_s00a2s_0_ooc.xdc

# XDC: /home/binh/BTL_HTN_GTN_final/la_bd_project/la_bd_project.gen/sources_1/bd/la_system/ip/la_system_smartconnect_0_0/bd_0/ip/ip_6/bd_94ec_sarn_0_ooc.xdc

# XDC: /home/binh/BTL_HTN_GTN_final/la_bd_project/la_bd_project.gen/sources_1/bd/la_system/ip/la_system_smartconnect_0_0/bd_0/ip/ip_7/bd_94ec_srn_0_ooc.xdc

# XDC: /home/binh/BTL_HTN_GTN_final/la_bd_project/la_bd_project.gen/sources_1/bd/la_system/ip/la_system_smartconnect_0_0/bd_0/ip/ip_8/bd_94ec_sawn_0_ooc.xdc

# XDC: /home/binh/BTL_HTN_GTN_final/la_bd_project/la_bd_project.gen/sources_1/bd/la_system/ip/la_system_smartconnect_0_0/bd_0/ip/ip_9/bd_94ec_swn_0_ooc.xdc

# XDC: /home/binh/BTL_HTN_GTN_final/la_bd_project/la_bd_project.gen/sources_1/bd/la_system/ip/la_system_smartconnect_0_0/bd_0/ip/ip_10/bd_94ec_sbn_0_ooc.xdc

# XDC: /home/binh/BTL_HTN_GTN_final/la_bd_project/la_bd_project.gen/sources_1/bd/la_system/ip/la_system_smartconnect_0_0/bd_0/ip/ip_11/bd_94ec_m00s2a_0_ooc.xdc

# XDC: /home/binh/BTL_HTN_GTN_final/la_bd_project/la_bd_project.gen/sources_1/bd/la_system/ip/la_system_smartconnect_0_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'la_system_smartconnect_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/binh/BTL_HTN_GTN_final/la_bd_project/la_bd_project.gen/sources_1/bd/la_system/ip/la_system_smartconnect_0_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'la_system_smartconnect_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
