# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/la_pins.xdc

# Block Designs: bd/la_system/la_system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==la_system || ORIG_REF_NAME==la_system} -quiet] -quiet

# IP: bd/la_system/ip/la_system_processing_system7_0_0/la_system_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==la_system_processing_system7_0_0 || ORIG_REF_NAME==la_system_processing_system7_0_0} -quiet] -quiet

# IP: bd/la_system/ip/la_system_logic_analyzer_top_0_0/la_system_logic_analyzer_top_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==la_system_logic_analyzer_top_0_0 || ORIG_REF_NAME==la_system_logic_analyzer_top_0_0} -quiet] -quiet

# IP: bd/la_system/ip/la_system_rst_ps7_0_200M_0/la_system_rst_ps7_0_200M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==la_system_rst_ps7_0_200M_0 || ORIG_REF_NAME==la_system_rst_ps7_0_200M_0} -quiet] -quiet

# IP: bd/la_system/ip/la_system_smartconnect_0_0/la_system_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==la_system_smartconnect_0_0 || ORIG_REF_NAME==la_system_smartconnect_0_0} -quiet] -quiet

# IP: bd/la_system/ip/la_system_clk_wiz_0_1/la_system_clk_wiz_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==la_system_clk_wiz_0_1 || ORIG_REF_NAME==la_system_clk_wiz_0_1} -quiet] -quiet

# XDC: /home/binh/BTL_HTN_GTN_final/la_bd_project/la_bd_project.gen/sources_1/bd/la_system/la_system_ooc.xdc
