# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/binh/BTL_HTN_GTN_final/la_bd_project/la_bd_project.srcs/sources_1/bd/la_system/ip/la_system_rst_ps7_0_200M_0/la_system_rst_ps7_0_200M_0.xci
# IP: The module: 'la_system_rst_ps7_0_200M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/binh/BTL_HTN_GTN_final/la_bd_project/la_bd_project.gen/sources_1/bd/la_system/ip/la_system_rst_ps7_0_200M_0/la_system_rst_ps7_0_200M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'la_system_rst_ps7_0_200M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/binh/BTL_HTN_GTN_final/la_bd_project/la_bd_project.gen/sources_1/bd/la_system/ip/la_system_rst_ps7_0_200M_0/la_system_rst_ps7_0_200M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'la_system_rst_ps7_0_200M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/binh/BTL_HTN_GTN_final/la_bd_project/la_bd_project.gen/sources_1/bd/la_system/ip/la_system_rst_ps7_0_200M_0/la_system_rst_ps7_0_200M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'la_system_rst_ps7_0_200M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/binh/BTL_HTN_GTN_final/la_bd_project/la_bd_project.srcs/sources_1/bd/la_system/ip/la_system_rst_ps7_0_200M_0/la_system_rst_ps7_0_200M_0.xci
# IP: The module: 'la_system_rst_ps7_0_200M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/binh/BTL_HTN_GTN_final/la_bd_project/la_bd_project.gen/sources_1/bd/la_system/ip/la_system_rst_ps7_0_200M_0/la_system_rst_ps7_0_200M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'la_system_rst_ps7_0_200M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/binh/BTL_HTN_GTN_final/la_bd_project/la_bd_project.gen/sources_1/bd/la_system/ip/la_system_rst_ps7_0_200M_0/la_system_rst_ps7_0_200M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'la_system_rst_ps7_0_200M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/binh/BTL_HTN_GTN_final/la_bd_project/la_bd_project.gen/sources_1/bd/la_system/ip/la_system_rst_ps7_0_200M_0/la_system_rst_ps7_0_200M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'la_system_rst_ps7_0_200M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
